# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://jcastillo7.github.io/hello_nbdev/"

git_url = "https://github.com/jcastillo7/hello_nbdev/tree/master/"

def custom_doc_links(name): return None
